#!/bin/bash
#
# Univention Container Mode - saml-restore
#
# Copyright 2020-2021 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

## util(s)
source /usr/lib/univention-container-mode/utils.sh || exit 1

## function(s)
# function name() { # name: (IN)[>(OUT)]
# 	echo function
# }

## ucr shell
eval "$(ucr shell hostname domainname kerberos/realm)"

## declare
declare -a ucrchanges
# ucrchanges+=("key=value")
declare -a ucrremoves
# ucrremoves+=("key")

declare -A ucrcounter
# ucrcounter[<STRING>]=<INT>

declare -A ucrcommit
# ucrcommit+=/<PATH>/<FILE> OR ucrcommit[<FILE>]=/<PATH>/<FILE>

debug "### START SCRIPT($(pwd)/$0) ###"
## saml restore from backup for container mode environment
#
restore=/var/backups/univention-container-mode
#
secret=/etc/simplesamlphp/ucs-sso-kerberos.secret
#
# restore only if we have a vaild backup ( join/99-system-restore-initialize )
[[ -f ${restore}/restore ]] && [[ -d ${restore}/saml ]] && {
	find ${restore}/saml -type f -name *.secret -exec /bin/bash -c 'secret={}; \
		echo "$(date --utc +%FT%T.%3NZ): $(</etc/simplesamlphp/$(basename ${secret}))" >> \
			/etc/simplesamlphp/$(basename ${secret}).old; \
		tr --delete "\n" <${secret}>  \
			/etc/simplesamlphp/$(basename ${secret}); \
		touch --no-dereference        \
			/etc/simplesamlphp/$(basename ${secret})' \;
	kinit --password-file=${secret} ucs\-sso@${kerberos_realm} && klist | egrep -- "krbtgt.*${kerberos_realm}$" && kdestroy
}
#
## saml restore from backup for container mode environment
debug "### STOPP SCRIPT($(pwd)/$0) ###"

## ucr removes
UniventionConfigRegistryUnSet ${ucrremoves[@]}

## ucr changes
UniventionConfigRegistrySet ${ucrchanges[@]}

## ucr commit
UniventionConfigCommit ${ucrcommit[@]}

## cleanup
unset \
	hostname \
	domainname \
	kerberos_realm \
	ucrchanges ucrremoves ucrcounter ucrcommit

debug "### CLEAN SCRIPT($(pwd)/$0) ###"
