#!/bin/bash
#
# Univention Container Mode - setup-system-container-role-common
#
# Copyright 2020-2021 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

## util(s)
source /usr/lib/univention-container-mode/utils.sh || exit 1

## function(s)
# function name() { # name: (IN)[>(OUT)]
# 	echo function
# }

## ucr shell
# eval "$(ucr shell hostname domainname)"

## declare
declare -a ucrchanges
# ucrchanges+=("key=value")
declare -a ucrremoves
# ucrremoves+=("key")

declare -A ucrcounter
# ucrcounter[<STRING>]=<INT>

declare -A ucrcommit
# ucrcommit+=/<PATH>/<FILE> OR ucrcommit[<FILE>]=/<PATH>/<FILE>

debug "### START SCRIPT($(pwd)/$0) ###"
## Setup system container role common for container mode environment
#
UniventionContainerRoleCommon="univention-container-role-common univention-container-role-server-common"
UniventionDockerContainerMode="univention-docker-container-mode"
#
UniventionRoleCommonRegEx='^\s\s(.*grub.*|.*initrd.*|.*memtest.*|.*linux.*image.*|Conflicts:|\s\s|.*<.*>|.*common$|.*univention-system-setup$|.*univention-network-manager$)'
#
command -v ps >/dev/null 2>&1 || UniventionInstall procps
#
[[ ! -e /var/univention-join/joined ]] && [[ ! -e /var/univention-join/status ]] &&
	if dpkg --compare-versions $(ucr get version/version).$(ucr get version/patchlevel) lt 5.0.1 || [[ $(ps --no-headers --pid 1 --format command) =~ /sbin/init && $(apt-cache depends ${UniventionContainerRoleCommon} | egrep -- "${UniventionDockerContainerMode}$") =~ ${UniventionDockerContainerMode} ]]; then
		cd /tmp &&
			for package in ${UniventionContainerRoleCommon}; do
				# get package, max 3 times ( connection timeout to repository mirror server )
				apt-get download ${package} || apt-get download ${package} || apt-get download ${package}
				# get package full name
				BuildPackage=$(ls -1 ${package}*deb)
				# extract, change depens and conficts finaly rebuild the package
				dpkg-deb --raw-extract ${BuildPackage} ${package}

				[[ -f ${package}/DEBIAN/control ]] &&
					if [[ ${package} =~ server ]]; then
						sed -i 's/^Depends.*$/Depends: univention-container-role-common/g' \
							${package}/DEBIAN/control
					else
						sed -i '/^Depends.*$/d' \
							${package}/DEBIAN/control
					fi

				dpkg-deb --build ${package} /var/cache/apt/archives/${BuildPackage}
				# install the modified package
				UniventionInstall /var/cache/apt/archives/${BuildPackage}
				apt-mark hold ${package}
				rm --force --recursive --verbose ${package} ${BuildPackage}
			done
	else
		UniventionInstall ${UniventionContainerRoleCommon}
	fi
#
for package in ${UniventionContainerRoleCommon//-container/}; do
	cache=/var/cache/univention-container-mode/depends.${package}.md5
	mkdir --parents $(dirname ${cache}) && touch ${cache}

	OldSum=$(<${cache})
	NewSum=$(apt-cache depends ${package} 2>/dev/null | md5sum | awk '{ print $1 }')

	[[ "${NewSum}" != "${OldSum}" ]] && {
		depends=$(
			apt-cache depends ${package} 2>/dev/null | egrep --invert-match -- ${UniventionRoleCommonRegEx} | awk '/Depends\:/{ printf " %s", $2 }'
		)
		recommends=$(
			apt-cache depends ${package} 2>/dev/null | egrep --invert-match -- ${UniventionRoleCommonRegEx} | awk '/Recommends\:/{ printf " %s", $2 }'
		)

		if [[ ${package} =~ server ]]; then
			UniventionInstall ${depends} ${recommends}
		else
			UniventionInstall ${depends}
		fi

		echo ${NewSum} >${cache}
	}

done
#
## Setup system container role common for container mode environment
debug "### STOPP SCRIPT($(pwd)/$0) ###"

## ucr removes
UniventionConfigRegistryUnSet ${ucrremoves[@]}

## ucr changes
UniventionConfigRegistrySet ${ucrchanges[@]}

## ucr commit
UniventionConfigCommit ${ucrcommit[@]}

## cleanup
unset \
	ucrchanges ucrremoves ucrcounter ucrcommit

debug "### CLEAN SCRIPT($(pwd)/$0) ###"
