#!/bin/bash
#
# Univention Container Mode - system-cleanup
#
# Copyright 2020-2021 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

## util(s)
source /usr/lib/univention-container-mode/utils.sh || exit 1

## function(s)
# function name() { # name: (IN)[>(OUT)]
# 	echo function
# }

## ucr shell
# eval "$(ucr shell hostname domainname)"

## declare
declare -a ucrchanges
# ucrchanges+=("key=value")
declare -a ucrremoves
# ucrremoves+=("key")

declare -A ucrcounter
# ucrcounter[<STRING>]=<INT>

declare -A ucrcommit
# ucrcommit+=/<PATH>/<FILE> OR ucrcommit[<FILE>]=/<PATH>/<FILE>

debug "### START SCRIPT($(pwd)/$0) ###"
## system cleanup for container mode environment
#
# clean default backup(s) from install
find /etc \
	-type f \
	-name "*.debian" \
	-exec rm --force --verbose {} \;
#
# clean ssl certificate backup(s) from install
find /etc/univention \
	-maxdepth 1 \
	-type d \
	-name "ssl.orig" \
	-exec rm --force --recursive --verbose {} \;
find /etc/univention \
	-maxdepth 1 \
	-type d \
	-name "ssl_*" \
	-exec rm --force --recursive --verbose {} \;
#
# clean systemd service unit file(s)
for unit in univention-welcome-screen; do
	find /etc/systemd/system /lib/systemd/system /usr/lib/systemd/system \
		-type l \
		-name "${unit}.service" \
		-exec rm --force --verbose {} \;
done
#
# reload systemd daemon
systemctl daemon-reload
#
# enable and start default service unit(s)
for service in atd bind9 cron nscd rsyslog slapd; do
	systemctl enable -- ${service}.service || /bin/true
	systemctl start -- ${service}.service || /bin/true
done
#
# start/restart/disable failed unit(s)
for unit in service socket; do
	for stat in start restart disable; do
		systemctl list-units --plain --state failed --type ${unit} | awk '/[a-z].*failed/{ print $1 }' | xargs --no-run-if-empty systemctl ${stat} -- 2>&1 || /bin/true
	done
done
#
# mask failed mount unit(s)
for unit in mount; do
	for stat in mask; do
		systemctl list-units --plain --state failed --type ${unit} | awk '/[a-z].*failed/{ print $1 }' | xargs --no-run-if-empty systemctl ${stat} -- 2>&1 || /bin/true
	done
done
#
## system cleanup for container mode environment
debug "### STOPP SCRIPT($(pwd)/$0) ###"

## ucr removes
UniventionConfigRegistryUnSet ${ucrremoves[@]}

## ucr changes
UniventionConfigRegistrySet ${ucrchanges[@]}

## ucr commit
UniventionConfigCommit ${ucrcommit[@]}

## cleanup
unset \
	ucrchanges ucrremoves ucrcounter ucrcommit

debug "### CLEAN SCRIPT($(pwd)/$0) ###"
